#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output HDMI-0  --left-of DP-5
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-5 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          8
bspc config normal_border_color  "#343F44"
bspc config active_border_color  "#393939"
bspc config focused_border_color "#A7C080"
bspc config presel_feedback_color "#A7C080"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a SFML state=floating

feh --bg-scale /home/charly/.config/bspwm/wallpaper.jpg
/home/charly/.config/polybar/launch.sh
